services:
  app:
    build:
      context: .
      target: dev
    ports:
      - 4001:4001
    environment:
      - PORT=4001
    depends_on:
      - postgres

  postgres:
    image: postgres:12.5
    environment:
      POSTGRES_DB: mvp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - 'db-data:/var/lib/postgresql/data'

volumes:
  db-data: {}
